var records = [
        {
            id: "42", lastName: "Harris", middleName: "Lee", firstName: "Richard", memberNum: "M930041",
            dob: "22 MAY 1975", streetAddr: "1001 Cleveland St", cityAddr: "Alexandria", stateAddr: "VA", zipAddr: "22312", zip4Addr: "",
            dateAdded:"09/15/2013", isBadAddress:"No",
            notes:"Lorem ipsum dolor sit amet, instructior reprehendunt definitionem ex sea. Natum copiosae est ea, sit ex quando fabellas necessitatibus."
        }
]

var dropdowns = [
    {
        name: 'usStates',
        options: [
            {id: 1, label: "Alabama", value: "AL", humanLabel: "AL", total: 0},
            {id: 2, label: "Alaska", value: "AK", humanLabel: "AK", total: 0},
            {id: 3, label: "American Samoa", value: "AS", humanLabel: "AS", total: 0},
            {id: 4, label: "Arizona", value: "AZ", humanLabel: "AZ", total: 0},
            {id: 5, label: "Arkansas", value: "AR", humanLabel: "AR", total: 0},
            {id: 6, label: "California", value: "CA", humanLabel: "CA", total: 0},
            {id: 7, label: "Colorado", value: "CO", humanLabel: "CO", total: 0},
            {id: 8, label: "Connecticut", value: "CT", humanLabel: "CT", total: 0},
            {id: 9, label: "Delaware", value: "DE", humanLabel: "DE", total: 0},
            {id: 10, label: "District Of Columbia", value: "DC", humanLabel: "DC", total: 0},
            {id: 11, label: "Federated States Of Micronesia", value: "FM", humanLabel: "FM", total: 0},
            {id: 12, label: "Florida", value: "FL", humanLabel: "FL", total: 0},
            {id: 13, label: "Georgia", value: "GA", humanLabel: "GA", total: 0},
            {id: 14, label: "Guam", value: "GU", humanLabel: "GU", total: 0},
            {id: 15, label: "Hawaii", value: "HI", humanLabel: "HI", total: 0},
            {id: 16, label: "Idaho", value: "ID", humanLabel: "ID", total: 0},
            {id: 17, label: "Illinois", value: "IL", humanLabel: "IL", total: 0},
            {id: 18, label: "Indiana", value: "IN", humanLabel: "IN", total: 0},
            {id: 19, label: "Iowa", value: "IA", humanLabel: "IA", total: 0},
            {id: 20, label: "Kansas", value: "KS", humanLabel: "KS", total: 0},
            {id: 21, label: "Kentucky", value: "KY", humanLabel: "KY", total: 0},
            {id: 22, label: "Louisiana", value: "LA", humanLabel: "LA", total: 0},
            {id: 23, label: "Maine", value: "ME", humanLabel: "ME", total: 0},
            {id: 24, label: "Marshall Islands", value: "MH", humanLabel: "MH", total: 0},
            {id: 25, label: "Maryland", value: "MD", humanLabel: "MD", total: 0},
            {id: 26, label: "Massachusetts", value: "MA", humanLabel: "MA", total: 0},
            {id: 27, label: "Michigan", value: "MI", humanLabel: "MI", total: 0},
            {id: 28, label: "Minnesota", value: "MN", humanLabel: "MN", total: 0},
            {id: 29, label: "Mississippi", value: "MS", humanLabel: "MS", total: 0},
            {id: 30, label: "Missouri", value: "MO", humanLabel: "MO", total: 0},
            {id: 31, label: "Montana", value: "MT", humanLabel: "MT", total: 0},
            {id: 32, label: "Nebraska", value: "NE", humanLabel: "NE", total: 0},
            {id: 33, label: "Nevada", value: "NV", humanLabel: "NV", total: 0},
            {id: 34, label: "New Hampshire", value: "NH", humanLabel: "NH", total: 0},
            {id: 35, label: "New Jersey", value: "NJ", humanLabel: "NJ", total: 0},
            {id: 36, label: "New Mexico", value: "NM", humanLabel: "NM", total: 0},
            {id: 37, label: "New York", value: "NY", humanLabel: "NY", total: 0},
            {id: 38, label: "North Carolina", value: "NC", humanLabel: "NC", total: 0},
            {id: 39, label: "North Dakota", value: "ND", humanLabel: "ND", total: 0},
            {id: 40, label: "Northern Mariana Islands", value: "MP", humanLabel: "MP", total: 0},
            {id: 41, label: "Ohio", value: "OH", humanLabel: "OH", total: 0},
            {id: 42, label: "Oklahoma", value: "OK", humanLabel: "OK", total: 0},
            {id: 43, label: "Oregon", value: "OR", humanLabel: "OR", total: 0},
            {id: 44, label: "Palau", value: "PW", humanLabel: "PW", total: 0},
            {id: 45, label: "Pennsylvania", value: "PA", humanLabel: "PA", total: 0},
            {id: 46, label: "Puerto Rico", value: "PR", humanLabel: "PR", total: 0},
            {id: 47, label: "Rhode Island", value: "RI", humanLabel: "RI", total: 0},
            {id: 48, label: "South Carolina", value: "SC", humanLabel: "SC", total: 0},
            {id: 49, label: "South Dakota", value: "SD", humanLabel: "SD", total: 0},
            {id: 50, label: "Tennessee", value: "TN", humanLabel: "TN", total: 0},
            {id: 51, label: "Texas", value: "TX", humanLabel: "TX", total: 0},
            {id: 52, label: "Utah", value: "UT", humanLabel: "UT", total: 0},
            {id: 53, label: "Vermont", value: "VT", humanLabel: "VT", total: 0},
            {id: 54, label: "Virgin Islands", value: "VI", humanLabel: "VI", total: 0},
            {id: 55, label: "Virginia", value: "VA", humanLabel: "VA", total: 0},
            {id: 56, label: "Washington", value: "WA", humanLabel: "WA", total: 0},
            {id: 57, label: "West Virginia", value: "WV", humanLabel: "WV", total: 0},
            {id: 58, label: "Wisconsin", value: "WI", humanLabel: "WI", total: 0},
            {id: 59, label: "Wyoming", value: "WY", humanLabel: "WY", total: 0}
        ]
    }
];